packages:
  ubuntu:
    common:
      packages:
        - python3-setuptools
        - zlib1g-dev
        - openssh-server
        - wget
        - curl
        - dnsmasq
        - nmap
        - ovmf
        - patch
        - psmisc
        - libvirt-clients
        - libvirt-dev
        - bridge-utils
        - jq
        - unzip
        - genisoimage
        - qemu-kvm
        - libguestfs-tools
        - gir1.2-polkit-1.0
        - libpolkit-agent-1-0
        - libpolkit-gobject-1-0
        - apache2-utils
        - netcat
    podman:
      packages:
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - software-properties-common
    bionic:
      packages:
        - libvirt-bin
        - libpolkit-backend-1-0
        - libssl1.0-dev
        - python3-bcrypt
    focal_jammy:
      packages:
        - apparmor
        - apparmor-profiles-extra
        - apparmor-utils
        - libvirt-daemon
        - libvirt-daemon-system
        - libssl-dev
    pip3:
    - python-apt
    - kubernetes==25.3.0
    - pyYAML
    - virtualbmc
    - lxml
    - netaddr
    - libvirt-python
    - six
    - docker-py
    - jmespath
    - passlib
  centos:
    common:
      packages:
        - bind-utils
        - curl
        - dnsmasq
        - edk2-ovmf
        - firewalld
        - genisoimage
        - httpd-tools
        - jq
        - libguestfs-tools
        - libguestfs-tools
        - libvirt
        - libvirt-daemon-kvm
        - libvirt-devel
        - NetworkManager
        - nmap
        - patch
        - polkit-pkla-compat
        - psmisc
        - python3-bcrypt
        - python3-libvirt
        - python3-lxml
        - python3-netaddr
        - python3-passlib
        - python3-six
        - qemu-kvm
        - unzip
        - vim-enhanced
        - virt-install
        - wget
    el8:
      packages:
        - network-scripts
        - redhat-lsb-core
    el9:
      packages:
        - NetworkManager-initscripts-updown
        - python3-requests-oauthlib
    pip3:
      - flask_oauthlib==0.9.6
      - jmespath
      - kubernetes==25.3.0
DAEMON_JSON_PATH: "{{ metal3_dir }}/vm-setup/roles/packages_installation/files"
CONTAINER_RUNTIME: "{{ lookup('env', 'CONTAINER_RUNTIME') }}"
OS_VERSION_ID: "{{ lookup('env', 'OS_VERSION_ID') }}"
REGISTRY: "{{ lookup('env', 'REGISTRY') }}"

MIRROR_DOCKER_IO: "{{ lookup('env', 'MIRROR_DOCKER_IO', default='') }}"


HTTP_PROXY: "{{ lookup('env', 'HTTP_PROXY', default='') }}"
HTTPS_PROXY: "{{ lookup('env', 'HTTPS_PROXY', default='') }}"
NO_PROXY: "{{ lookup('env', 'NO_PROXY', default='') }}"

EXTERNAL_SUBNET_V4: "{{ lookup('env', 'EXTERNAL_SUBNET_V4', default='192.168.111.0/24') }}"
EXTERNAL_SUBNET_V6: "{{ lookup('env', 'EXTERNAL_SUBNET_V6', default='fd55::/64') }}"
PROVISIONING_SUBNET_V4: "{{ lookup('env', 'PROVISIONING_SUBNET_V4', default='172.23.23.0/24') }}"
PROVISIONING_SUBNET_V6: "{{ lookup('env', 'PROVISIONING_SUBNET_V6', default='fd56::/64') }}"

POD_CIDR: "{{ lookup('env', 'POD_CIDR') }}"
SERVICE_CIDR: "10.96.0.0/12"
BARE_METAL_PROVISIONER_NETWORK: "{{ lookup('env', 'BARE_METAL_PROVISIONER_NETWORK') | default('172.22.0.0/24', true) }}"

NO_PROXY_STR: "{{ NO_PROXY }}, {{ POD_CIDR }}, {{ SERVICE_CIDR }}, {{ BARE_METAL_PROVISIONER_NETWORK }}, {{ EXTERNAL_SUBNET_V4 }}, {{ EXTERNAL_SUBNET_V6 }}, {{ PROVISIONING_SUBNET_V4 }}, {{ PROVISIONING_SUBNET_V6 }}"
NO_PROXY_CLEANED: "{{ NO_PROXY_STR  | replace(' ', '') |split(',') | ansible.netcommon.ipaddr | join(',') }}"