  - name: Define number of BMH's
    set_fact:
      NUMBER_OF_BMH: "{{ NUM_OF_MASTER_REPLICAS|int +  NUM_OF_WORKER_REPLICAS|int }}"

  - name: Untaint all nodes.
    shell: |
        kubectl taint nodes --all node-role.kubernetes.io/master-
    environment:
      KUBECONFIG: "/tmp/kubeconfig-{{ CLUSTER_NAME }}.yaml"
    ignore_errors: yes

  - name: Scale worker down to 0.
    k8s:
      api_version: cluster.x-k8s.io/{{ CAPI_VERSION }}
      kind: MachineDeployment
      name: "{{ CLUSTER_NAME }}"
      namespace: "{{ NAMESPACE }}"
      kubeconfig: "/tmp/kubeconfig-{{ CLUSTER_NAME }}.yaml"
      definition:
        spec:
          replicas: 0

  - name: Wait until worker is scaled down and one bmh is Ready
    k8s_info:
      api_version: metal3.io/v1alpha1
      kind: BareMetalHost
      namespace: "{{ NAMESPACE }}"
      kubeconfig: "/tmp/kubeconfig-{{ CLUSTER_NAME }}.yaml"
    register: bmhs
    retries: 200
    delay: 20
    until:
      - bmhs is succeeded
      - bmhs.resources | filter_provisioning("ready") | length == 1

  - name: Scale worker back to 1.
    k8s:
      api_version: cluster.x-k8s.io/{{ CAPI_VERSION }}
      kind: MachineDeployment
      name: "{{ CLUSTER_NAME }}"
      namespace: "{{ NAMESPACE }}"
      kubeconfig: "/tmp/kubeconfig-{{ CLUSTER_NAME }}.yaml"
      definition:
        spec:
          replicas: 1

  - name: Wait until all "{{ NUMBER_OF_BMH }}" BMH are provisioned
    k8s_info:
      api_version: metal3.io/v1alpha1
      kind: BareMetalHost
      namespace: "{{ NAMESPACE }}"
      kubeconfig: "/tmp/kubeconfig-{{ CLUSTER_NAME }}.yaml"
    register: bmhs
    retries: 200
    delay: 20
    until:
      - bmhs is succeeded
      - bmhs.resources | filter_provisioning("provisioned") | length == (NUMBER_OF_BMH | int)

  - name: Wait until "{{ NUMBER_OF_BMH }}" machines become running.
    k8s_info:
      api_version: cluster.x-k8s.io/{{ CAPI_VERSION }}
      kind: machines
      namespace: "{{ NAMESPACE }}"
      kubeconfig: "/tmp/kubeconfig-{{ CLUSTER_NAME }}.yaml"
    register: machines
    retries: 200
    delay: 20
    until:
      - machines is succeeded
      - machines.resources | filter_phase("running") | length == (NUMBER_OF_BMH | int)
